on:
  push:
    paths:
      - 'src/**'
jobs:
  src:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aviate-labs/setup-dfx@v0.2.2
        with:
          dfx-version: 0.8.1
          install-moc: true
      - run: for i in src/*.mo ; do moc --check $i ; done
