on:
  push:
    paths:
      - 'src/**'
      - 'test/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aviate-labs/setup-dfx@v0.2.2
        with:
          dfx-version: 0.8.1
          install-moc: true
      - run: for i in test/*.mo ; do moc --package base $(dfx cache show)/base -r $i ; done
